services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ./app_data/database:/var/lib/postgresql/data
      - ./app_data/logs/postgres:/var/postgres/logs
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 10s
      retries: 3

  redis:
    container_name: redis
    image: redis

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 10s
      retries: 3


  bot:
    container_name: rpsls_bot
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "main.py"
    restart: on-failure
    volumes:
      - ./static:/bot/static
      - ./app_data/logs/bot:/bot/logs
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  nginx:
      container_name: nginx
      restart: on-failure
      image: nginx
      env_file:
        - .env
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        - ./app_data/logs/nginx:/var/log/nginx
        - ./static:/www/data/static
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy