services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command:
      - "postgres"
      - "-c"
      - "log_destination=stderr"
      - "-c"
      - "logging_collector=on"
      - "-c"
      - "log_directory=/tmp/logs"
    volumes:
      - ./app_data/database:/var/lib/postgresql/data
      - ./app_data/logs/postgres:/var/postgres/logs
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U admin
      interval: 10s
      timeout: 10s
      retries: 3

  redis:
    container_name: redis
    image: redis

    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 10s
      timeout: 10s
      retries: 3


  bot:
    container_name: rpsls_bot
    build:
      dockerfile: ./Dockerfile
    command:
      - "python"
      - "main.py"
    restart: on-failure
    volumes:
      - /var/www/zwick.fun/html/static:/bot/static
      - ./app_data/logs/bot:/bot/logs
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy